language: node_js
node_js:
  - 12.7.0
addons:
  ssh_known_hosts:
  - 142.93.231.114
branches:
  only:
  - master
  - creating-layout
  - develop
env:
  global:
  - REMOTE_APP_DIR="/var/www/html/sw-heroes.git"
  - REMOTE_USER="travis"
  - REMOTE_EMAIL="travis@planecq.com"
  - REMOTE_HOST="142.93.231.114"
before_install:
  - openssl aes-256-cbc -K $encrypted_b3adf7fe1d17_key -iv $encrypted_b3adf7fe1d17_iv
    -in .travis/deploy.enc -out deploy -d
  - chmod 600 deploy
  - mv deploy ~/.ssh/travis_rsa
install:
  - npm install
before_script:
  - if [ $TRAVIS_BRANCH = "master" ]; then export PUBLIC_PATH='/sw-heroes/'; else export PUBLIC_PATH='/sw-heroes/dev/'; fi
  - echo $PUBLIC_PATH
script:
  - npm run dev
deploy:
  skip_cleanup: true
  provider: script
  script:
    - sh ./.travis/deploy.sh
  on:
    all_branches: true
notifications:
  email: false
