export const REQUEST_STARTED = 'REQUEST_STARTED';
export const REQUEST_FAILED = 'REQUEST_FAILED';
export const REQUEST_PEOPLE = 'REQUEST_PEOPLE';
export const REQUEST_PERSON = 'REQUEST_PERSON';
export const REQUEST_PEOPLE_SUCCESS = 'REQUEST_PEOPLE_SUCCESS';
export const REQUEST_PERSON_SUCCESS = 'REQUEST_PERSON_SUCCESS';