export const REQUEST_PEOPLE = 'REQUEST_PEOPLE';
export const REQUEST_PEOPLE_SUCCESS = 'REQUEST_PEOPLE_SUCCESS';
export const REQUEST_PEOPLE_STARTED = 'REQUEST_PEOPLE_STARTED';
export const REQUEST_PEOPLE_FAILED = 'REQUEST_PEOPLE_FAILED';

export const REQUEST_PERSON = 'REQUEST_PERSON';
export const REQUEST_PERSON_SUCCESS = 'REQUEST_PERSON_SUCCESS';
export const REQUEST_PERSON_STARTED = 'REQUEST_PERSON_STARTED';
export const REQUEST_PERSON_FAILED = 'REQUEST_PERSON_FAILED';

export const REQUEST_DATA = 'REQUEST_DATA';
export const REQUEST_DATA_SUCCESS = 'REQUEST_DATA_SUCCESS';
